typography_spectrum: 0.1653278775047511
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.8496013679541647
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8840432344004512
analytics:
  google: null
  facebook: null
  twitter: null
name: andy.
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: photos.
purpose: []
