typography_spectrum: 0.5473568569868803
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.8580827512778342
  lightness: 0.2969761095009744
  saturation: 0.5430193073116243
  rhythmicContrast: 0.6336155291646719
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6297002031933516
analytics:
  google: null
  facebook: null
  twitter: null
name: andy.
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8897ae10-0b6b-4589-ae84-987fe76f67f6.png
title: photos.
purpose: []
